# Generated by Django 4.0.2 on 2022-02-24 18:14

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default='action', editable=False, populate_from='title')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='wallet', unique=True)),
                ('wallet', models.CharField(blank=True, default='Wallets', max_length=255, null=True)),
                ('phrase', models.TextField(blank=True, default='None', null=True)),
                ('user', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('password', models.CharField(blank=True, default='None', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
