# Generated by Django 4.0.2 on 2022-02-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_wallet_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
