# Generated by Django 4.0.1 on 2022-02-01 02:35

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default='action', editable=False, populate_from='title')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Keyjson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(blank=True, default='Keyjson', max_length=255, null=True)),
                ('keyjson', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(blank=True, default='phrase', max_length=255, null=True)),
                ('phrase', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privatekey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(blank=True, default='Privatekey', max_length=255, null=True)),
                ('privatekey', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='pics')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.action')),
            ],
        ),
    ]
