# Generated by Django 4.0.1 on 2022-02-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_wallet_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='purpose',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.action'),
        ),
    ]
